version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/Test_Bolid
    ports:
      - "0.0.0.0:8000:8000"

    env_file:
      - .env
    depends_on:
      - db

  tests:
    build: .
    command: pytest tests/
    depends_on:
      - db
      - web


volumes:
  postgres_data:
